# PR triggers in ADO are configured using branch policies. This section is only for GitHub.
pr:
- master

# Disable CI trigger (defaults to all branches)
trigger: none

variables:
- template: settings/common.yml

jobs:
- job:
  pool:
    name: $(AgentPool)
  workspace:
    clean: all
  steps:
  - checkout: self
    clean: true
    submodules: true
  - template: templates/common.yml
