# PR triggers in ADO are configured using branch policies. This section is only for GitHub.
pr:
- master

# Disable CI trigger (defaults to all branches)
trigger: none

variables:
- template: settings/common.yml

resources:
  repositories:
  - repository: build-tools
    type: git
    endpoint: Analog
    name: Analog/mixedrealitytoolkit.build
    ref: mru-ue

jobs:
- job:
  pool:
    name: $(AgentPool)
  # uncomment after switching to UE4.25
  #variables:
  #  - template: settings/ue425undefs.yml
  workspace:
    clean: all
  steps:
  - checkout: self
    clean: true
    submodules: true
  - checkout: build-tools
  - template: templates/common.yml
  - task: PowerShell@2
    displayName: 'Check git history'
    inputs:
      targetType: 'filePath'
      filePath: $(UXTSourceDir)\Tools\scripts\CheckHistory.ps1
      workingDirectory: $(UXTSourceDir)